### ISSUE TITLE
from .ss2d_ablations import SS2D_ForwardCoreSpeedAblations, SS2D_ForwardCoreModeAblations, cross_selective_scanv2

### ISSUE THREAD

**Issue by WhyBlue** [walking-shadow/Official_Remote_Sensing_Mamba#6]
from .ss2d_ablations import SS2D_ForwardCoreSpeedAblations, SS2D_ForwardCoreModeAblations, cross_selective_scanv2
from ss2d_ablations import SS2DDev

I configured the environment as required, but the above two imports are still not found. What should I do? Furthermore, what is their roles?

**Comment by walking-shadow** [comment]
Actually, these libraries are not necessary at all. They are packages used by the author of VMamba for some exploratory experiments. In this project, since forward_type is set to 'v2', these libraries are not actually imported. If you wish to further understand and use these libraries, you can refer to the [VMamba](https://github.com/MzeroMiko/VMamba) project.

**Comment by LPeng625** [comment]
> Actually, these libraries are not necessary at all. They are packages used by the author of VMamba for some exploratory experiments. In this project, since forward_type is set to 'v2', these libraries are not actually imported. If you wish to further understand and use these libraries, you can refer to the [VMamba](https://github.com/MzeroMiko/VMamba) project.

您好，如果我想跑ss1d和ss2d，应该如何更改代码和配置

**Comment by changanXIAO** [comment]
意思就是不用管这个库是吗
