### ISSUE TITLE
Pre-trained models

### ISSUE THREAD

**Issue by YupeiLin2388** [walking-shadow/Official_Remote_Sensing_Mamba#9]
Your work is impressive! I was wondering if there's a possibility of releasing pre-trained models?

**Comment by walking-shadow** [comment]
Since our Remote Sensing Mamba utilizes a simple model architecture and training method, it is intended as a baseline to demonstrate the potential of SSM-based models in ultra-high resolution remote sensing dense prediction tasks. Therefore, we did not save the pretrained model. The training of Remote Sensing Mamba is also very straightforward, allowing you to retrain it yourself. By incorporating some effective modules and data augmentation methods, you should be able to further improve the model's performance.
